apiVersion: v1
kind: PersistentVolume
metadata:
  name: measurements-pv
  namespace: homelab
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /home/ubuntu/homelab-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - ubuntu

