apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: measurements-pvc 
  namespace: homelab
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
