---
- name: Installing Zsh and git
  apt: pkg=zsh,git state=latest
  register: installation
  become: true

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Check if dotfiles exists
  stat:
    path: ~/.dotfiles
  register: stat_dotfiles_result

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists

- name: Delete automatically generate .zshrc
  ansible.builtin.file:
    path: ~/.zshrc
    state: absent

- name: Cloning dotfiles
  shell: |
    git clone --bare https://github.com/RW21/dotfiles.git $HOME/.dotfiles
    alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
    dotfiles config --local status.showUntrackedFiles no
    echo ".dotfiles" >> $HOME/.gitignore
    dotfiles checkout
  when: not stat_dotfiles_result.stat.exists

