- name: Untar exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus-community/smartctl_exporter/releases/download/v0.9.1/smartctl_exporter-0.9.1.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move executable
  become: yes
  ansible.builtin.copy:
    src: /tmp/smartctl_exporter-0.9.1.linux-amd64/smartctl_exporter
    dest: /usr/local/bin/smartctl_exporter
    mode: '0755'
    remote_src: yes

- name: Template smartctl_exporter.service
  become: yes
  ansible.builtin.template:
    src: smartctl_exporter.service.j2
    dest: /etc/systemd/system/smartctl_exporter.service
    mode: '0644'
  notify: reload systemctl

- name: Start the service
  become: yes
  ansible.builtin.systemd:
    name: smartctl_exporter.service
    state: started
    enabled: yes
