# [webservers]
# lark-server.local  ansible_ssh_user=rw21-server
# orangepi3.local    ansible_ssh_user=orangepi
# ubuntu.local       ansible_ssh_user=ubuntu

# [webservers:vars]
# ansible_ssh_private_key_file=/home/rw21/.ssh/id_rsa

webservers:
  hosts:
    ubuntu.local:
      ansible_ssh_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3

  vars:
    ansible_ssh_private_key_file: /home/rw21/.ssh/id_rsa
    timezone: JP

