all:
  children:
    webservers:
      hosts:
        192.168.193.179:
          ansible_user: ubuntu
          ansible_host: 192.168.193.179

    worker-nodes:
      hosts:
        192.168.193.38:
          ansible_user: ubuntu

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: /home/rw21/.ssh/id_rsa
    timezone: JP
    container_repository_endpoint: http://192.168.193.179:5000
