---
- name: Ansible Playbook for configuring new general servers
  hosts: webservers
  roles:
    - { role: general, tags: general }
    - { role: zsh, tags: zsh }
    - { role: docker, tags: docker }
    - { role: smb, tags: smb}
    - { role: compose, tags: compose}
    - { role: nfs, tags: nfs}
    - { role: pihole, tags: pihole }
    - { role: reverse-proxy, tags: reverse-proxy}
    - { role: co2, tags: co2}
    - { role: bme280, tags: bme280}
  remote_user: rw21-server
  become: yes
