---
- name: Ansible Playbook for configuring new general servers
  hosts: webservers
  roles:
    - { role: general, tags: general }
    - { role: zsh, tags: zsh }
    - { role: docker, tags: docker }
    - { role: smb, tags: smb}
    - { role: nfs, tags: nfs}
    - { role: pihole, tags: pihole }
    - { role: bme280, tags: bme280}
    - { role: container-registry, tags: container-registry}
  become: yes
